pipeline {
    agent none
    stages {
        stage('build') {
            agent {
                docker {
                    image 'python:3.9.2' 
                }
            }
            steps {
                sh 'pip install virtualenv && virtualenv env && . env/bin/activate && pip install -r backend/requirements.txt'
            }
        }
        stage('test') {
            agent {
                docker {
                    image 'python:3.9.2' 
                }
            }
            steps {
                sh 'pip install virtualenv && virtualenv env && . env/bin/activate && pip install -r backend/requirements.txt && python backend/tests.py'
            }
        }
    }
}