pipeline {
    agent { docker { image 'python:3.9.2' } }
    stages {
        stage('build') {
            steps {
                sh 'python -m virtualenv venv && . venv/bin/activate && pip install -r backend/requirements.txt && python backend/app.py'
            }
        }
        stage('test') {
            steps {
                sh 'python -m virtualenv venv && . venv/bin/activate && pip install -r backend/requirements.txt && python backend/tests.py'
            }
        }
    }
}